config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  get "up" => "rails/health#show", as: :rails_health_check
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.local?

  devise_for :users
  unauthenticated { root to: "home#landing" }
  authenticated(:user) { root to: "home#dashboard", as: :authenticated_root }

  resources :projects do
    resources :comments, only: %i[new create], default: { commentable_type: "Project" }
  end

  resources :comments, only: %i[edit update destroy]
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :trackable, polymorphic: true
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  has_rich_text :description

  belongs_to :commentable, polymorphic: true
  belongs_to :user
end

app/models/project.rb
class Project < ApplicationRecord
  attr_accessor :current_action_user

  belongs_to :user
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :activities, as: :trackable, dependent: :destroy

  enum :status, { draft: 0, appoved: 1, delivered: 2 }
  validates :title, :details, presence: true

  after_update_commit do
    self.activities.create!(user: current_action_user, event: "#{current_action_user.email} changed status to #{status} from #{saved_changes[:status].first} ") if saved_change_to_status?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :projects, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  # allow_browser versions: :modern
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :commentable, only: %i[ new create ]
  before_action :comment, only: %i[ edit update destroy ]
  def new
    @comment = commentable.comments.build(comment_params)
  end

  def create
    @comment = commentable.comments.build(comment_params)
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.turbo_stream
        format.html { redirect_to project_path(commentable), notice: "Comment created successfully" }
      else
        format.turbo_stream
      end
    end
  end

  def edit
  end

  def update
    comment.update(comment_params)
  end

  def destroy
    comment.destroy
  end

  private

  def commentable
    model = params[:default][:commentable_type].constantize
    if model == Project
      @commentable ||= Project.find(params[:project_id])
    end
  end

  def comment
    @comment ||= Comment.find(params[:id])
  end

  def comment_params
    params.expect(comment: [ :description ])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, only: :landing
  def dashboard
  end

  def landing
    redirect_to authenticated_root_path if user_signed_in?
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects
  def index
    @projects = Project.all
  end

  # GET /projects/1
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  def create
    @project = current_user.projects.build(project_params)

    if @project.save
      redirect_to @project, notice: "Project was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /projects/1
  def update
    if @project.update(project_params.merge(current_action_user: current_user))
      redirect_to @project, notice: "Project was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /projects/1
  def destroy
    @project.destroy!
    redirect_to projects_path, notice: "Project was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.expect(project: [ :title, :details, :status ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/comments/_comment.html.erb
<div id=<%= dom_id(comment)%> class="max-w-sm p-6 bg-white border border-gray-200 rounded-lg shadow-sm dark:bg-gray-800 dark:border-gray-700">
    <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white"><%= comment.description %></h5>
  <p class="mb-3 font-normal text-gray-700 dark:text-gray-400"><%= comment.user&.email %></p>
  <%= link_to edit_comment_path(comment), class: "inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" do %>
    Edit
  <% end %>
  <%= button_to comment_path(comment), method: :delete, class: "inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-red-700 rounded-lg hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-red-300 dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-800" do %>
    Destroy
  <% end %>
</div>

app/views/comments/_form.html.erb
<%= form_with(model: [commentable, Comment.new], url: form_url, class: "contents") do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul class="list-disc ml-6">
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.rich_text_area :description, rows: 4, class: ["block shadow-sm rounded-md border outline-hidden px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": comment.errors[:details].none?, "border-red-400 focus:outline-red-600": comment.errors[:details].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/comments/create.turbo_stream.erb
<%= turbo_stream.prepend "project_comments", @comment %>
<%= turbo_stream.update "project_new_comment" do %>
  <%= render 'comments/form', comment: @commentable.comments.build, commentable: @commentable, form_url: project_comments_path(@commentable) %>
<% end %>

app/views/comments/destroy.turbo_stream.erb
<%= turbo_stream.remove @comment %>

app/views/comments/edit.html.erb
<div>
  <h1 class="font-bold text-4xl">Comments#edit</h1>
  <p>Find me in app/views/comments/edit.html.erb</p>
</div>

app/views/comments/new.html.erb
<div>
  <h1 class="font-bold text-4xl">Comments#new</h1>
  <p>Find me in app/views/comments/new.html.erb</p>
</div>

app/views/home/dashboard.html.erb
<div>
  <h1 class="font-bold text-4xl">Welcome, <%= current_user.email%>!</h1>
  <br/>
  <p>Start by adding your new projects</p>
</div>

app/views/home/landing.html.erb
<section class="bg-white dark:bg-gray-900">
  <div class="py-8 px-4 mx-auto max-w-screen-xl text-center lg:py-16">
    <h1 class="mb-4 text-4xl font-extrabold tracking-tight leading-none text-gray-900 md:text-5xl lg:text-6xl dark:text-white">Wlelcome to Project Management App</h1>
    <p class="mb-8 text-lg font-normal text-gray-500 lg:text-xl sm:px-16 lg:px-48 dark:text-gray-400">Here at Flowbite we focus on markets where technology, innovation, and capital can unlock long-term value and drive economic growth.</p>
    <div class="flex-col space-y-4 sm:flex-row sm:justify-center sm:space-y-0">
      <%= link_to new_user_session_path, class: "inline-flex justify-center items-center py-3 px-5 text-base font-medium text-center text-white rounded-lg bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 dark:focus:ring-blue-900" do %>
        Sign In to continue
        <svg class="w-3.5 h-3.5 ms-2 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9"/>
        </svg>
      <% end %>
      <a href="#" class="py-3 px-5 sm:ms-4 text-sm font-medium text-gray-900 focus:outline-none bg-white rounded-lg border border-gray-200 hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-4 focus:ring-gray-100 dark:focus:ring-gray-700 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:text-white dark:hover:bg-gray-700">
        Learn more
      </a>
    </div>
  </div>
</section>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Project Management" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <div class="container mx-auto mt-[10px] px-5">
      <%= render 'shared/alerts' %>
    </div>
    <main class="container mx-auto mt-28 px-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project, class: "contents") do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul class="list-disc ml-6">
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: ["block shadow-sm rounded-md border outline-hidden px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": project.errors[:title!].none?, "border-red-400 focus:outline-red-600": project.errors[:title!].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :status %>
    <%= form.select :status, Project.statuses.keys.map{ |s| [s.humanize, s] }, {}, {class: ["block shadow-sm rounded-md border outline-hidden px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": project.errors[:title!].none?, "border-red-400 focus:outline-red-600": project.errors[:title!].any?}]} %>
  </div>

  <div class="my-5">
    <%= form.label :details %>
    <%= form.textarea :details, rows: 4, class: ["block shadow-sm rounded-md border outline-hidden px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": project.errors[:details].none?, "border-red-400 focus:outline-red-600": project.errors[:details].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Title:</strong>
    <%= project.title %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Status:</strong>
    <%= project.status.humanize %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Details:</strong>
    <%= project.details %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">User:</strong>
    <%= project.user.email %>
  </p>
</div>

app/views/projects/edit.html.erb
<% content_for :title, "Editing project" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing project</h1>

  <%= render "form", project: @project %>

  <%= link_to "Show this project", @project, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to projects", projects_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/projects/index.html.erb
<% content_for :title, "Projects" %>

<div class="w-full">
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Projects</h1>
    <%= link_to "New project", new_project_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="projects" class="min-w-full">
    <% if @projects.any? %>
      <% @projects.each do |project| %>
        <%= render project %>
        <p>
          <%= link_to "Show this project", project, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
        </p>
      <% end %>
    <% else %>
      <p class="text-center my-10">No projects found.</p>
    <% end %>
  </div>
</div>

app/views/projects/new.html.erb
<% content_for :title, "New project" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New project</h1>

  <%= render "form", project: @project %>

  <%= link_to "Back to projects", projects_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/projects/show.html.erb
<% content_for :title, "Showing project" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Showing project</h1>

  <%= render @project %>

  <%= link_to "Edit this project", edit_project_path(@project), class: "mt-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to projects", projects_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <div class="inline-block ml-2">
    <%= button_to "Destroy this project", @project, method: :delete, class: "mt-2 rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium" %>
  </div>
</div>

<div id="project_new_comment">
  <%= render 'comments/form', comment: Comment.new, commentable: @project, form_url: project_comments_path(@project) %>
</div>

<div id="project_comments">
  <%= render @project.comments %>
</div>

<br/>
<hr/>
<% @project.activities.each_with_index do | activity, index |%>
  <div>
    <p><%= index + 1 %> | <%= activity.event %> | Made by:<%= activity.user.email %><p>
  </div>
<% end %>

app/views/shared/_alerts.html.erb
<% if flash[:notice].present? %>
  <div class="p-4 mb-4 text-sm text-blue-800 rounded-lg bg-blue-50 dark:bg-gray-800 dark:text-blue-400" data-controller="auto-dismiss-alert" role="alert">
    <span class="font-medium">Info alert!</span> <%= notice %>
  </div>
<% end %>

<% if flash[:alert].present? %>
  <div class="p-4 mb-4 text-sm text-green-800 rounded-lg bg-green-50 dark:bg-gray-800 dark:text-green-400" data-controller="auto-dismiss-alert" role="alert">
    <span  pan class="font-medium">Success alert!</span> <%= alert %>
  </div>
<% end %>

app/views/shared/_header.html.erb
<nav class="bg-gray-800 text-white p-4">
  <div class="container mx-auto flex justify-between items-center">
    <%= link_to "Project Management", root_path, class: "text-xl font-bold" %>
    <div class="space-x-4">
      <%= link_to "Home", authenticated_root_path, class: "hover:text-gray-400" %>
      <%= link_to "Projects", projects_path, class: "hover:text-gray-400" %>
      <%= link_to "About", "#", class: "hover:text-gray-400" %>
      <%= link_to "Contact", '#', class: "hover:text-gray-400" %>
    </div>
    <div class="flex">
      <% if user_signed_in? %>
        <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "hover:text-red-400" %>
      <% else %>
        <%= link_to "Sign In", new_user_session_path, class: "hover:text-gray-400 mr-4" %>
        <%= link_to "Sign Up", new_user_registration_path, class: "hover:text-gray-400" %>
      <% end %>
    </div>
  </div>
</nav>